articles/urls.py
from django.urls import path
from articles import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index),
    path('dinner/<str:name>/', views.dinner),
    path('review/', views.review, name='review'),
    path('create_review/', views.create_review, name='create_review'),
]

django_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('foods/', include('foods.urls')),
]

foods/urls.py
from django.urls import path
from articles import views

urlpatterns = []

# 네이버 API 이용하여 검색 결과 저장하기

articles/models.py
from turtle import title
from django.db import models

# Create your models here.


class Article(models.Model):  # 상속
    # id 는 자동으로 만들어진다.
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

foods/models.py
from django.db import models

# Create your models here.

articles/views.py
from django.shortcuts import render, redirect
import random
from .models import Article

# Create your views here.


def index(request):
    return render(request, 'index.html')


def dinner(request, name):
    menus = [{"name": '족발', "price": 30000}, {"name": '햄버거', "price": 5000}, {
        "name": '치킨', "price": 20000}, {"name": '초밥', "price": 15000}]
    pick = random.choice(menus)  # 랜덤으로 딕셔너리 목록을 골라줌
    articles = Article.objects.order_by('-pk')
    context = {
        'pick': pick,
        'name': name,
        'menus': menus,
        'articles': articles,
    }
    return render(request, 'dinner.html', context)


def review(request):
    return render(request, 'review.html')


def create_review(request):
    content = request.POST.get('content')
    title = request.POST.get('title')
    article = Article(title=title, content=content)
    article.save()
    print(request.POST)

    return redirect('/articles/dinner/무언가/')

foods/views.py
from django.shortcuts import render

# Create your views here.

articles/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <title>오늘 뭐 먹지?</title>
</head>

<body class="container">
    {% block content %}{% endblock %}
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</body>

</html>

articles/templates/dinner.html
{% extends 'base.html' %}{% block content %}
<h1>오늘 {{ name }}님의 저녁은 {{ pick.name }} 입니다.</h1>
<h1>메뉴 리스트</h1>
<ul>
    {% for menu in menus %}
    <li>{{ menu.name }} {{ menu.price }}원</li>
    {% endfor %}
</ul>

{% if pick.price > 20000 %}
<p>비싸다!!</p>
{% elif pick.price > 10000 %}
<p>해볼만하다!!</p>
{% else %}
<p>맛있겠다!!</p>
{% endif %}

<h1>리뷰 리스트</h1>
{% for article in articles %}
<p>글 번호: {{ article.pk }} </p>
<p>글 제목: {{ article.title }}</p>
<p>글 내용: {{ article.content }}</p>
<hr />
{% endfor %} {% endblock %}

articles/templates/index.html
<h1>거북이반 화이팅!</h1>

articles/templates/review.html
{% extends 'base.html' %} {% block content %}
<form class="form-group" action="{% url 'articles:create_review' %}" method="post">
    {% csrf_token %}
    <label for="title">Title: </label>
    <input class="form-control" type="text" name="title" /><br />
    <label for="control">Content: </label>
    <textarea class="form-control" name="content" cols="30" rows="5"></textarea><br />
    <input type="submit" />

</form>

{% endblock %}

articles/templates/review_result.html
<h1>보내서 받은 내용은 {{ content }}야!</h1>